
const MainPage = () => {
    return (
        <div>
            <p>MainPage</p>
            <p>MainPage</p>
            <p>MainPage</p>
            <p>MainPage</p>
            <p>MainPage</p>
            <p>MainPage</p>
            <p>MainPage</p>
            <p>MainPage</p>
            <p>MainPage</p>
            <p>MainPage</p>
            <p>MainPage</p>
            <p>MainPage</p>
            <p>MainPage</p>
            <p>MainPage</p>
            <p>MainPage</p>
            <p>MainPage</p>
            <p>MainPage</p>
            <p>MainPage</p>
            <p>MainPage</p>
            <p>MainPage</p>
            <p>MainPage</p>
            <p>MainPage</p>
            <p>MainPage</p>
            <p>MainPage</p>
            <p>MainPage</p>
            <p>MainPage</p>
            <p>MainPage</p>
            <p>MainPage</p>
            <p>MainPage</p>
            <p>MainPage</p>
            <p>MainPage</p>
            <p>MainPage</p>
            <p>MainPage</p>
            <p>MainPage</p>
            <p>MainPage</p>
            <p>MainPage</p>
            <p>MainPage</p>
            <p>MainPage</p>
            <p>MainPage</p>
            <p>MainPage</p>
            <p>MainPage</p>
            <p>MainPage</p>
            <p>MainPage</p>
            <p>MainPage</p>
            <p>MainPage</p>
            <p>MainPage</p>
            <p>MainPage</p>
            <p>MainPage</p>
            <p>MainPage</p>
            <p>MainPage</p>
            <p>MainPage</p>
            <p>MainPage</p>
            <p>MainPage</p>
            <p>MainPage</p>
            <p>MainPage</p>
            <p>MainPage</p>
            <p>MainPage</p>
            <p>MainPage</p>
            <p>MainPage</p>
            <p>MainPage</p>
        </div>
    )
}

export default MainPage